import { Book } from './book.vm';

export const LibraryData: Book[] = [
  {
    id: 1,
    title: 'Don Quijote de la Mancha',
    author: 'Miguel de Cervantes',
    cover: '/images/don-quijote.webp',
    status: 'read',
    available: true,
    genres: 'Historical Fiction',
  },
  {
    id: 2,
    title: 'Orgullo y prejuicio',
    author: 'Jane Austen',
    cover: '/images/orgullo-prejuicio.webp',
    status: 'read',
    available: true,
    genres: 'Romance',
  },
  {
    id: 3,
    title: 'Cien años de soledad',
    author: 'Gabriel García Márquez',
    cover: '/images/cien-anos-soledad.webp',
    status: 'want-to-read',
    available: false,
    genres: 'Historical Fiction',
  },
  {
    id: 4,
    title: '1984',
    author: 'George Orwell',
    cover: '/images/1984.webp',
    status: 'want-to-read',
    available: true,
    genres: 'Science Fiction',
  },
  {
    id: 5,
    title: 'Crimen y castigo',
    author: 'Fiódor Dostoievski',
    cover: '/images/crimen-castigo.webp',
    status: 'read',
    available: true,
    genres: 'Mystery',
  },
  {
    id: 6,
    title: 'El conde de Montecristo',
    author: 'Alexandre Dumas',
    cover: '/images/conde-montecristo.webp',
    status: 'read',
    available: true,
    genres: 'Historical Fiction',
  },
  {
    id: 7,
    title: 'La Odisea',
    author: 'Homero',
    cover: '/images/odisea.webp',
    status: 'want-to-read',
    available: true,
    genres: 'Fantasy',
  },
  {
    id: 8,
    title: 'Frankenstein',
    author: 'Mary Shelley',
    cover: '/images/frankenstein.webp',
    status: 'read',
    available: true,
    genres: 'Science Fiction',
  },
  {
    id: 9,
    title: 'El gran Gatsby',
    author: 'F. Scott Fitzgerald',
    cover: '/images/gran-gatsby.webp',
    status: 'did-not-finish',
    available: true,
    genres: 'Historical Fiction',
  },
  {
    id: 10,
    title: 'La metamorfosis',
    author: 'Franz Kafka',
    cover: '/images/metamorfosis.webp',
    status: 'read',
    available: true,
    genres: 'Mystery',
  },
  {
    id: 11,
    title: 'Los miserables',
    author: 'Victor Hugo',
    cover: '/images/miserables.webp',
    status: 'want-to-read',
    available: false,
    genres: 'Historical Fiction',
  },
  {
    id: 12,
    title: 'Cumbres borrascosas',
    author: 'Emily Brontë',
    cover: '/images/cumbres-borrascosas.webp',
    status: 'read',
    available: true,
    genres: 'Romance',
  },
  {
    id: 13,
    title: 'Moby Dick',
    author: 'Herman Melville',
    cover: '/images/moby-dick.webp',
    status: 'want-to-read',
    available: false,
    genres: 'Historical Fiction',
  },
  {
    id: 14,
    title: 'El extranjero',
    author: 'Albert Camus',
    cover: '/images/extranjero.webp',
    status: 'read',
    available: true,
    genres: 'Mystery',
  },
  {
    id: 15,
    title: 'Hamlet',
    author: 'William Shakespeare',
    cover: '/images/hamlet.webp',
    status: 'read',
    available: true,
    genres: 'Historical Fiction',
  },
  {
    id: 16,
    title: 'El retrato de Dorian Gray',
    author: 'Oscar Wilde',
    cover: '/images/dorian-gray.webp',
    status: 'want-to-read',
    available: false,
    genres: 'Fantasy',
  },
  {
    id: 17,
    title: 'Madame Bovary',
    author: 'Gustave Flaubert',
    cover: '/images/madame-bovary.webp',
    status: 'did-not-finish',
    available: true,
    genres: 'Romance',
  },
  {
    id: 18,
    title: 'El Principito',
    author: 'Antoine de Saint-Exupéry',
    cover: '/images/principito.webp',
    status: 'read',
    available: true,
    genres: 'Fantasy',
  },
  {
    id: 19,
    title: 'Divina Comedia',
    author: 'Dante Alighieri',
    cover: '/images/divina-comedia.webp',
    status: 'want-to-read',
    available: false,
    genres: 'Fantasy',
  },
  {
    id: 20,
    title: 'Una habitación propia',
    author: 'Virginia Woolf',
    cover: '/images/habitacion-propia.webp',
    status: 'in-progress',
    available: true,
    genres: 'Historical Fiction',
  },
];
