/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HousesRouteRouteImport } from './routes/houses/route'
import { Route as HousesIndexRouteImport } from './routes/houses/index'
import { Route as HousesIdRouteImport } from './routes/houses/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HousesRouteRoute = HousesRouteRouteImport.update({
  id: '/houses',
  path: '/houses',
  getParentRoute: () => rootRouteImport,
} as any)
const HousesIndexRoute = HousesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HousesRouteRoute,
} as any)
const HousesIdRoute = HousesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => HousesRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/houses': typeof HousesRouteRouteWithChildren
  '/houses/$id': typeof HousesIdRoute
  '/houses/': typeof HousesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/houses/$id': typeof HousesIdRoute
  '/houses': typeof HousesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/houses': typeof HousesRouteRouteWithChildren
  '/houses/$id': typeof HousesIdRoute
  '/houses/': typeof HousesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/houses' | '/houses/$id' | '/houses/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/houses/$id' | '/houses'
  id: '__root__' | '/' | '/houses' | '/houses/$id' | '/houses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HousesRouteRoute: typeof HousesRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/houses': {
      id: '/houses'
      path: '/houses'
      fullPath: '/houses'
      preLoaderRoute: typeof HousesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/houses/': {
      id: '/houses/'
      path: '/'
      fullPath: '/houses/'
      preLoaderRoute: typeof HousesIndexRouteImport
      parentRoute: typeof HousesRouteRoute
    }
    '/houses/$id': {
      id: '/houses/$id'
      path: '/$id'
      fullPath: '/houses/$id'
      preLoaderRoute: typeof HousesIdRouteImport
      parentRoute: typeof HousesRouteRoute
    }
  }
}

interface HousesRouteRouteChildren {
  HousesIdRoute: typeof HousesIdRoute
  HousesIndexRoute: typeof HousesIndexRoute
}

const HousesRouteRouteChildren: HousesRouteRouteChildren = {
  HousesIdRoute: HousesIdRoute,
  HousesIndexRoute: HousesIndexRoute,
}

const HousesRouteRouteWithChildren = HousesRouteRoute._addFileChildren(
  HousesRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HousesRouteRoute: HousesRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
