name: CI Workflow

on:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./lab-module06-testing

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 12

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
          cache-dependency-path: lab-module06-testing/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        env:
          PNPM_ONLY_BUILT_DEPENDENCIES: "cypress"

      - name: Install Cypress Binary
        run: pnpm exec cypress install

      - name: Unit tests
        run: pnpm test

      - name: E2E tests
        run: pnpm run test:e2e:ci

      - name: Upload screenshots
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: lab-module06-testing/cypress/screenshots

      - name: Upload videos
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: lab-module06-testing/cypress/videos
