import type { Dish } from '@/types'

export const dishes: Dish[] = [
  {
    id: '1',
    name: 'Avocado Toast',
    description: 'Toasted bread topped with smashed avocado and cherry tomatoes.',
    category: 'Breakfast',
    weekDay: 'Monday',
    isFavorite: false,
  },
  {
    id: '2',
    name: 'Chicken Caesar Salad',
    description: 'Grilled chicken served with romaine lettuce, parmesan, and Caesar dressing.',
    category: 'Lunch',
    weekDay: 'Tuesday',
    isFavorite: false,
  },
  {
    id: '3',
    name: 'Spaghetti Bolognese',
    description: 'Classic pasta with a rich beef and tomato sauce.',
    category: 'Dinner',
    weekDay: 'Wednesday',
    isFavorite: true,
  },
  {
    id: '4',
    name: 'Blueberry Pancakes',
    description: 'Fluffy pancakes served with fresh blueberries and maple syrup.',
    category: 'Breakfast',
    weekDay: 'Thursday',
    isFavorite: false,
  },
  {
    id: '5',
    name: 'Turkey Sandwich',
    description: 'Whole-grain bread filled with turkey, lettuce, tomato, and cheese.',
    category: 'Lunch',
    weekDay: 'Friday',
    isFavorite: true,
  },
  {
    id: '6',
    name: 'Grilled Salmon',
    description: 'Fresh salmon fillet served with steamed vegetables.',
    category: 'Dinner',
    weekDay: 'Saturday',
    isFavorite: false,
  },
  {
    id: '7',
    name: 'Greek Yogurt Bowl',
    description: 'Greek yogurt topped with granola, honey, and fresh berries.',
    category: 'Breakfast',
    weekDay: 'Sunday',
    isFavorite: false,
  },
  {
    id: '8',
    name: 'Vegetable Stir-Fry',
    description: 'Mixed vegetables sautéed with soy sauce and served over rice.',
    category: 'Lunch',
    weekDay: 'Monday',
    isFavorite: false,
  },
  {
    id: '9',
    name: 'Beef Tacos',
    description: 'Soft tortillas filled with seasoned beef, lettuce, cheese, and salsa.',
    category: 'Dinner',
    weekDay: 'Tuesday',
    isFavorite: true,
  },
  {
    id: '10',
    name: 'Mushroom Omelette',
    description: 'Three-egg omelette with sautéed mushrooms and cheddar cheese.',
    category: 'Breakfast',
    weekDay: 'Wednesday',
    isFavorite: false,
  },
]
